### ISSUE TITLE
How to save and load models trained using Godot

### ISSUE THREAD

**Issue by kerodkibatu** [asieradzk/RL_Matrix#11]
Hey there, I'm curious about how to save and load models trained using Godot. I've been experimenting with reinforcement learning algorithms, and now I'm at a point where I want to persist my trained models for future use. Can anyone guide me through the process? Any tips or examples would be greatly appreciated! Thanks in advance!

**Comment by asieradzk** [comment]
Hi Kerod.

Thanks for trying RL Matrix. I am in the process of making it a lot more polished and I'll be ditching binary serialiser for buffer saving.

I never exposed the saving method for Godot and currently if I remember correctly its deleted/commented out.

Are you using DQN or PPO? I might be able to publish something today for you. But there will be small breaking changes.

**Comment by kerodkibatu** [comment]
Thanks a lot for the prompt response! I'm currently using **PPO**.

**Comment by asieradzk** [comment]
> Thanks a lot for the prompt response! I'm currently using **PPO**.

Thats a shame. I'm a bit behind on this one. Let's see what I can do.

**Comment by asieradzk** [comment]
Just an update that I have commited an updated version. Its not on nuget yet

For you this means massive performance improvements for both PPO & DQN. Also RNN now works as intended and I am satisfied with it.

I have exposed save/load methods temporarily in the TrainingManagerBaseDiscrete so you'll have to find opportune time to access it (in between frame updates) or edit it yourself - let me know if you need help.

You may have to change some of your implementations as IEnvironment as been replaced with Async variant to enable some weird DRL experiments...
