### ISSUE TITLE
Avalonia support for 2d examples is broken

### ISSUE THREAD

**Issue by Nshtk** [asieradzk/RL_Matrix#17]
Hi.

It seems that CartPole example doesn't show any graphics if ```AvaloniaEnvViewer.Factory``` is passed to ```CartPoleEnv```, specifically ```myEnv.Render()``` does nothing. I tried to install Avalonia in a separate project and create a simple form to display an image returned by ```myEnv.Render()```, but if the Avalonia is installed ```myEnv.Render()``` throws  strange exception: ```'Could not load file or assembly 'Avalonia.DesktopRuntime, Version=0.10.18.0'. The system cannot find the file specified.'``` 
If the Avalonia doesn't work, then the crossplatform support for 2d is borked.

Although it may be more of a Gym.NET issue, but as it is no longer actively maintained, I posted this issue here.

**Comment by asieradzk** [comment]
There are no Avalonia examples. I never even tried Avalonia so I cant know if Gym.NET works alright with it (doubt). If youre on mac/linux I recommend you try Console/Godot for your first Hello World.
