### ISSUE TITLE
Introduce Test Driven Development!

### ISSUE THREAD

**Issue by GeorgeS2019** [asieradzk/RL_Matrix#8]
It is now possible to do Test Driven Development using VS2022 to create Gym 2D and 3D RL environments for testing

using the [latest](https://github.com/MikeSchulze/gdUnit4Mono/pull/37) gdUnit4API **TestAdaptor** on VS2022

![Z0nhScGr3J](https://github.com/MikeSchulze/gdUnit4Mono/assets/49812372/7d2ed607-0750-4b6e-80f7-e5913aec040e)

**Comment by asieradzk** [comment]
Sounds like something I need especially since when introducing changes I can break learning for some use-cases and unit tests wont catch it - only benchmarks.
